### ISSUE TITLE
Bug: kimup-controller loop restart

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/kube-image-updater#119]
kimup-controller
```
...
spec:
      containers:
      - args:
        - --healthz
        - --healthz-port=0
        - --healthz-path=/healthz
        - --metrics
        - --metrics-port=0
        - --metrics-path=/metrics
        - --loglevel=info
...
livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: kimup
        ports:
        - containerPort: 9080
          name: metrics
          protocol: TCP
        - containerPort: 9081
          name: healthz
          protocol: TCP
...
```
