### ISSUE TITLE
Bug: Alert discord canot send notification

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/kube-image-updater#121]
In logs
```
2m37s                      Warning   Execute action           Image/demo                    Error executing action alert-discord: secrets "discord-secret" is forbidden: User "system:serviceaccount:kimup-operator:kimup" cannot get resource "secrets" in API group "" in the namespace "default"
```

**Comment by dmicheneau** [comment]
workaround manifest role.yaml
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kimup-role
rules:
...
- apiGroups:
   - ""
  resources:
  - secrets
  verbs:
  - get
```
