### ISSUE TITLE
Add option node affinity by OS version in our manifest

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/kube-image-updater#62]
the purpose is to deploy kimup on a node where support the hardware compute is compile

**Comment by azrod** [comment]
Example

```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
```
