### ISSUE TITLE
[BUG] Wrong TAG when rules type is always

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/kube-image-updater#67]
Example

```
apiVersion: kimup.cloudavenue.io/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: kube-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: demo
  namespace: default
spec:
  image: ghcr.io/azrod/golink
  baseTag: v0.0.19
  triggers:
    - type: crontab
      value: "* 00 */12 * * *"
  rules:
    - name: golink-semver
      type: always
      actions:
        - type: apply
```

Result:

```
NAME   IMAGE                        TAG            
demo   ghcr.io/azrod/golink   v0.0.2-amd64  
```

Expected: the TAG is not superior to BaseTag
