### ISSUE TITLE
Doc: Error in Installation chapter

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/kube-image-updater#98]
- Missing namespace installation for kimup-controller

Add namespace kimup-operator for deploying kimup-controller
```
apiVersion: kimup.cloudavenue.io/v1alpha1
kind: Kimup
metadata:
  labels:
    app.kubernetes.io/name: kube-image-updater
  name: kimup
  namespace: kimup-operator
spec:
  name: demo
  logLevel: info
```

- wrong link for Image, AlertConfig and Kimup
